version: '3.4'

x-common-django:
  &default-common-django
  build:
    context: ../
    dockerfile: deployment/docker/Dockerfile
  environment:
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_USERNAME=${DATABASE_USERNAME}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}

    - DATABASE_AIM_NAME=${DATABASE_AIM_NAME}
    - DATABASE_AIM_HOST=${DATABASE_AIM_HOST}
    - DATABASE_AIM_PORT=${DATABASE_AIM_PORT}
    - DATABASE_AIM_USERNAME=${DATABASE_AIM_USERNAME}
    - DATABASE_AIM_PASSWORD=${DATABASE_AIM_PASSWORD}

    - ADMIN_USERNAME=${ADMIN_USERNAME}
    - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    - ADMIN_EMAIL=${ADMIN_EMAIL}
    # hardcoded
    - RABBITMQ_HOST=rabbitmq
    - DJANGO_SETTINGS_MODULE=core.settings.prod
    - VIRTUAL_HOST=amlit.com
    - VIRTUAL_PORT=8080
    - PYTHONPATH=/django-helpdesk
  volumes:
    - ../django_project:/home/web/django_project
    - ../django-helpdesk/helpdesk:/django-helpdesk/helpdesk
    - ./volumes/static:/home/web/static
    - ./volumes/media:/home/web/media
    - ./volumes/logs:/var/log/
  restart: on-failure

services:
  # Vanilla RabbitMQ service. This is needed by celery
  rabbitmq:
    image: rabbitmq:3.7-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  db:
    image: kartoza/postgis:11.5-2.8
    volumes:
      - ./backups:/backups
      - database:/var/lib/postgresql/data/
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - USERNAME=${DATABASE_USERNAME}
      - PASS=${DATABASE_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    restart: on-failure:5

  dbbackups:
    image: kartoza/pg-backup:9.6
    hostname: pg-backups
    volumes:
      - ./backups:/backups
    environment:
      # take care to let the project name below match that
      # declared in the top of the makefile
      - DUMPPREFIX=PG_amlit
      # These are all defaults anyway, but setting explicitly in
      # case we ever want to ever use different credentials
      - PGDATABASE=${DATABASE_NAME}
      - PGHOST=${DATABASE_HOST}
      - PGUSER=${DATABASE_USERNAME}
      - PGPASSWORD=${DATABASE_PASSWORD}
      - PGPORT=5432
    restart: on-failure:5

  django:
    <<: *default-common-django
    command: 'uwsgi --ini /uwsgi.conf'

# TODO:
#  Can't run the entrypoint
#    entrypoint: ["/entrypoint.sh"]

  web:
    image: nginx
    hostname: nginx
    volumes:
      - ./sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static:ro
      - ./volumes/media:/home/web/media:ro
      - ./volumes/logs:/var/log/nginxs
    ports:
      - "${HTTP_HOST}:8080"
    restart: on-failure:5

  # QGIS openquake
  qgis-server:
    image: openquake/qgis-server:3.16.2-ubuntu
    environment:
      # Do not run the embedded copy of nginx
      SKIP_NGINX: "true"
      # Improve rendering performance
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
      # Verbose logging
      QGIS_SERVER_LOG_LEVEL: 0
    volumes:
      - ./volumes/qgis-server/data:/io/data:ro
      - ./qgis-server/pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
    ports:
      - "9993:9993"
      - "9990:80"
    restart: on-failure:5

  # django application for development
  dev:
    <<: *default-common-django
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile-dev
    ports:
      # for django test server
      - "6002:8080"
      # for ssh
      - "6003:22"
    depends_on:
      - qgis-server
volumes:
  database:
  rabbitmq:
